config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  namespace :api, defaults: {format: :json} do

    resources :users, except: [:new, :edit, :destroy, :update]

    resource :session, only: [:create, :show, :destroy, :update]

    resources :subs, except: [:new, :edit]

    resources :posts, except: [:new, :edit] do
      post :upvote, on: :member
      post :downvote, on: :member
      post :clear_vote, on: :member
      member do
        resources :comments, except: [:new, :edit, :index] do
          post :upvote, on: :member
          post :downvote, on: :member
          post :clear_vote, on: :member
        end
      end
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :modded_subs,
    class_name: "Sub",
    foreign_key: :user_id,
    primary_key: :id

  has_many :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy

  has_many :votes,
    class_name: "Vote",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy

  has_many :comments, dependent: :destroy

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_token
    self.save!
    session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_token
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    wrap_parameters false

    def index
      @users = User.all
      render :index
    end

    def create
      @user = User.new(user_params)

      if @user.save
        log_in!(@user)
        render :show
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    def show
      @user = User.includes(:comments, :posts, :votes).find(params[:id]);
      render :show
    end

    private

    def user_params
      params.require(:user).permit(:username, :location, :prof_img, :email, :password)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action=" <%= users_url %>" method="post">
  <%= form_auth %>

  <%= render "layouts/user_session_form" %>

  <input type="submit" value="Sign Up">
  <input type="reset" value="Reset">
</form>

app/views/users/show.html.erb
<% if @user.prof_img %>
  <img src="<%= image_path(@user.prof_img) %>" alt="prof-pic" class="prof-pic">
<% end %>
<h1><%= @user.username %></h1>
<h3>Email: <%= @user.email %></h3>
<% if @user.location %>
<h3>Location: <%= @user.location %></h3>
<% end %>
<hr class="no-clear">
<h3>Latest Posts</h3>
<ul class="no-em">
  <% last_posts = @user.posts.order(created_at: :desc).limit(5) %>
  <% last_posts.each do |post| %>
    <li>
      <a href="<%= post_url(post) %>"><%= post.title %></a> in
      <% post.subs.each do |sub| %>
        <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
        <% if sub != post.subs.last %>, <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<hr class="no-clear">
<h3>Latest Comments</h3>
<ul class="no-em">
  <% last_comments = @user.comments.order(created_at: :desc).limit(5) %>
  <% last_comments.each do |comment| %>
    <li>
      <a href="<%= comment_url(comment) %>"><%= comment.content[0..30] %>(...)</a> on
      <a href="<%= post_url(comment.post) %>"><%= comment.post.title %></a> in
      <% comment.post.subs.each do |sub| %>
        <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
        <% if sub != comment.post.subs.last %>, <% end %>
      <% end %>
    </li>
  <% end %>
</ul>