config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  namespace :api, defaults: {format: :json} do

    resources :users, except: [:new, :edit, :destroy, :update]

    resource :session, only: [:create, :show, :destroy, :update]

    resources :subs, except: [:new, :edit]

    resources :posts, except: [:new, :edit] do
      post :upvote, on: :member
      post :downvote, on: :member
      post :clear_vote, on: :member
      member do
        resources :comments, except: [:new, :edit, :index] do
          post :upvote, on: :member
          post :downvote, on: :member
          post :clear_vote, on: :member
        end
      end
    end

  end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  after_save :set_stamp

  belongs_to :mod,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :posts,
    through: :post_subs,
    source: :post

  has_many :post_subs, dependent: :destroy

  def set_stamp
    self.update_columns(last_activity_stamp: self.updated_at)
  end
end

app/controllers/api/subs_controller.rb
module Api
  class SubsController < ApplicationController
    wrap_parameters false

    before_action :ensure_logged_in, only: [:create, :update, :destroy]
    before_action :ensure_moderator, only: [:update, :destroy]

    def index
      @subs = Sub.all.order(last_activity_stamp: :desc).includes(:mod)
      render :index
    end

    def create
      @sub = current_user.modded_subs.new(sub_params)

      if @sub.save
        render json: @sub
      else
        render json: @sub.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      @sub = current_sub
      if @sub.update(sub_params)
        render json: @sub
      else
        render json: @sub.errors.full_messages, status: :unprocessable_entity
      end
    end

    def show
      @sub = current_sub
      @posts = @sub.posts.page(params[:page])
      render :show
    end

    def destroy
      current_sub.delete
      render json: {}
    end

    private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end

    def ensure_moderator
      render status: :unprocessable_entity unless current_sub.mod == current_user
    end

    def current_sub
      Sub.find(params[:id])
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<label for="title">Title</label>
<input type="text" name="sub[title]" id="title" value="<%= @sub.title %>">

<label for="description">Description</label>
<input type="text" name="sub[description]" id="description"value="<%= @sub.description %>">
<hr>
<input type="submit" value="Submit">
<input type="reset" value="Reset">

app/views/subs/_post.html.erb
<li class="clearfix">
  <div class="vote_container">
   <form action="<%= upvote_post_url(post) %>" method="post">
     <%= form_auth %>
     <button>^</button>
   </form>
   <p><%= post.score %></p>
   <form action="<%= downvote_post_url(post) %>" method="post">
     <%= form_auth %>
     <button>v</button>
   </form>
 </div>
  <p><a href="<%= post_url(post) %>"><%= post.title %></a>
  <% if current_user == post.author %>
     - <a href="<%= edit_post_url(post) %>">edit</a>
  <% end %>
  </p>
  <p>by <a href="<%= user_url(post.author) %>"><%= post.author.username %></a> @ <%= post.created_at.to_s(:long) %>
    <% if fp %>
      in
      <% post.post_subs.each do |post_sub| %>
        <a href="<%= sub_url(post_sub.sub_id) %>"><%= post_sub.sub.title %></a>,
      <% end %>
    <% end %>
    ;
    <a href="<%= post_url(post) %>/#comments"><%= post.comments.count %> comments</a></p>
</li>

app/views/subs/edit.html.erb
<h1>Edit your sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= form_auth %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete sub"> (THIS IS IRREVERSIBLE)
</form>
<hr>
<form action=" <%= sub_url(@sub) %>" method="post">
  <%= form_auth %>
  <input type="hidden" name="_method" value="PATCH">

  <%= render "form" %>

</form>
<p><a href="<%= sub_url(@sub) %>">Back to sub</a></p>

app/views/subs/index.html.erb
<h1>Front Page</h1>

<ul class="votable clearfix">
<% @posts.order(last_activity_stamp: :desc).each do |post| %>
  <li>
    <%= render "post", post: post, fp: true %>
  </li>
<% end %>
</ul>

<a href="<%= new_sub_url %>">Create a sub</a>

app/views/subs/new.html.erb
<h1>Create a sub</h1>

<form action=" <%= subs_url %>" method="post">
  <%= form_auth %>
  <%= render "form" %>

</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<ul class="votable clearfix">
  <% @sub.posts.order(last_activity_stamp: :desc).each do |post| %>
    <%= render "post", post: post, fp: false %>
  <% end %>
</ul>
<a href="<%= new_post_url %>?sub_id=<%= @sub.id %>">New Post</a>