config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  namespace :api, defaults: {format: :json} do

    resources :users, except: [:new, :edit, :destroy, :update]

    resource :session, only: [:create, :show, :destroy, :update]

    resources :subs, except: [:new, :edit]

    resources :posts, except: [:new, :edit] do
      post :upvote, on: :member
      post :downvote, on: :member
      post :clear_vote, on: :member
      member do
        resources :comments, except: [:new, :edit, :index] do
          post :upvote, on: :member
          post :downvote, on: :member
          post :clear_vote, on: :member
        end
      end
    end

  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :user_id, presence: true
  after_save :set_stamp

  belongs_to :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :post_subs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  has_many :subs,
  through: :post_subs,
  source: :sub,
  dependent: :destroy

  def comments_by_parent_id
    comment_hash = Hash.new { |h, k| h[k] = [] }
    self.comments.order(updated_at: :desc).each do |comment|
      comment_hash[comment.parent_comment_id] << comment
    end

    comment_hash
  end

  def score
    score = 0
    self.votes.each do |vote|
      score += vote.value
    end

    score
  end

  def set_stamp
    self.update_columns(last_activity_stamp: self.updated_at)   #skip the callback
    self.subs.each do |sub|
      sub.update(last_activity_stamp: self.updated_at)
    end
  end

end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    wrap_parameters false

    before_action :ensure_sub, only: :create
    before_action :ensure_logged_in, only: [:create, :update, :destroy]
    before_action :ensure_author, only: [:update, :destroy]

    def index
      @posts = Post.all.order(last_activity_stamp: :desc).includes(:author, :votes, :subs).page(params[:page])         #this is the front page
      render :index
    end

    def show
      @post = current_post
      @all_comments = @post.comments.includes(:author).order(created_at: :desc)
      @comment_hash = @post.comments_by_parent_id
      render :show
    end

    def create
      sub_ids = post_params[:sub_id].map(&:to_i)
      pars_for_post = post_params
      pars_for_post.delete_if { |k, v| k == "sub_id" }
      @post = current_user.posts.new(pars_for_post)
      if @post.save
        @post.sub_ids = sub_ids
        @all_comments = @post.comments
        @comment_hash = @post.comments_by_parent_id
        render :show
      else
        render json: @post.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      @post = current_post
      sub_ids = post_params[:sub_id].map(&:to_i)
      pars_for_post = post_params
      pars_for_post.delete_if { |k, v| k == "sub_id" }

      if @post.update(pars_for_post)
        @post.sub_ids = sub_ids
        @all_comments = @post.comments.includes(:author).order(created_at: :desc)
        @comment_hash = @post.comments_by_parent_id
        render :show
      else
        render json: @post.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      current_post.delete
      render json: {}
    end

    def upvote
      @post = current_post
      delete_vote
      Vote.create!(value: 1, votable_type: "Post", votable_id: @post.id, user_id: current_user.id)
      render :blurb
    end

    def downvote
      @post = current_post
      delete_vote
      Vote.create!(value: -1, votable_type: "Post", votable_id: @post.id, user_id: current_user.id)
      render :blurb
    end

    def clear_vote
      delete_vote
      render :blurb
    end


    private

    def post_params
      params.require(:post).permit(:title, :url, :content, :user_id, :sub_id => [])
    end

    def current_post
      Post.includes(:subs).find(params[:id])
    end

    def delete_vote
      @post = current_post
      prior_vote = current_user.votes.where(votable_type: 'Post', votable_id: @post.id);

      Vote.destroy(prior_vote) if !prior_vote.empty?
    end

    def ensure_sub
      render status: :unprocessable_entity if post_params[:sub_id].empty?
    end

    def ensure_author
      render status: :unprocessable_entity unless current_user.id == current_post.user_id
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def has_children?(comment)
    @comment_hash.any? { |k, _| k == comment.id }
  end

  def display_children_comments(comment)
    a=""
     a += <<-HTML
      <li class="clearfix">

        <div class="vote_container clearfix">
        <form action="#{ upvote_comment_url(comment) }" method="post">
          #{form_auth}
          <button>^</button>
        </form>
        <p>#{comment.score}</p>
        <form action="#{ downvote_comment_url(comment) }" method="post">
          #{form_auth}
          <button>v</button>
        </form>
        </div>
        <h5><a href="#{user_url(comment.author)}">#{comment.author.username}</a> @ #{comment.created_at.to_s(:long)}:</h5>
        <p>#{comment.content}</p>

        <p class="reply_link"><a href="#{comment_url(comment)}">reply</a></p>

      </li>
    HTML
    if has_children?(comment)
      a += "<ul>"
      @comment_hash[comment.id].each do |c2|
        a += "#{display_children_comments(c2)}"
      end
      a += "</ul>"
    end
    return a.html_safe
  end
end

app/views/posts/_form.html.erb
<%= form_auth %>

<label for="title">Title*</label>
<input type="text" name="post[title]" id="title" value="<%= @post.title %>">

<label for="url">URL</label>
<input type="text" name="post[url]" id="url" value="<%= @post.url %>">

<label for="content">Content</label>
<textarea name="post[content]" id="content"><%= @post.content %></textarea>

<label for="sub">Post to sub*</label>
  <% Sub.all.each do |sub| %>
    <input type="checkbox" name="post[sub_id][]" id="sub_id_<%= sub.id %>" value="<%= sub.id %>"
      <%= "checked" if params[:sub_id].to_i == sub.id || @post.sub_ids.include?(sub.id) %>
    >
    <label for="sub_id_<%= sub.id %>"><%= sub.title %></label>
  <% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <%= form_auth %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete post">
</form>

<hr>
<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= render "form" %>
  <hr>
  <input type="submit" value="Edit post">
  <input type="reset" value="Reset">

</form>

<p><a href="<%= post_url(@post) %>">Return to post</a></p>

app/views/posts/new.html.erb
<h1>New post</h1>

<form action="<%= posts_url %>" method="post">

  <%= render "form" %>
  <hr>
  <input type="submit" value="Create post">
  <input type="reset" value="Reset">

</form>

<p><a href="<%= subs_url %>">Return to subs</a></p>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h4>posted in
  <% @post.subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>,
  <% end %>
  by <a href="<%= user_url(@post.author) %>"><%= @post.author.username %></a> @ <%= @post.created_at.to_s(:long) %>
</h4>

<% if current_user == @post.author %>
  <h5><a href="<%= edit_post_url(@post) %>">edit</a></h5>
<% end %>

<p><a href="<%= @post.url %>"><%= @post.url %></a></p>
<p><%= @post.content %></p>

<% if !@post.comments.empty? %>
<hr>
<h3 id="comments">Comments</h3>
  <ul class="votable comments">
  <% top_level_comments = @all_comments.where("parent_comment_id IS NULL") %>
  <% top_level_comments.each do |comment| %>
      <%= display_children_comments(comment) %>
  <% end %>
  </ul>
<% end %>
<hr>

<h3>Add a Comment</h3>
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" value="<%= params[:id] %>" name="comment[post_id]">
  <%= render "comments/new_comment" %>
</form>